### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [klausib/event_layer#2]
Especially when compared to lrs plugin

**Comment by klausib** [comment]
The event layer plugin creats event themes (Memory Layers with Point/Multipoint or Line/Multiline geometry) using linear referencing functions (locate_between, locate_along) analog to postgis functions. The result can be stored in the QGIS Project file and is dynamic, that means, is recalculated if data in the Event Table Changes. It support the creation of point layers and line layers, both with possible offset according to a fix value or data stored in the EventTable. It supports the same functionality, that ESRIs ArcView 3.x prozess "Dynamic Segementation" had.

**Comment by pcav** [comment]
This is what I expected, but AFAIK is what also LRS plugin does. Am I wrong?
Sorry to bother, but we are struggling keeping duplication at a minimum.

**Comment by klausib** [comment]
No Problem, I dont know anything about the LRS Plugin. But in 2011, when we contacted Sourcepole to write a Plugin with this special Functionality, there was now similar Plugin Available, that's for sure. The QGIS Core Application had to be modified by Marco for this Plugin! So the LRS Plugin came afterwards, I Suggest. So your questions should be asked to this author, I guess. But I dont mind, if you think the Sourcepole Plugin is a copy of LRS and not necessary, just delete it from the Plugin Repository.

**Comment by pcav** [comment]
In fact there was, but was using only PostGIS as a backend.
What I'm trying to do here is reduce redundancy: if this plugin brings new useful functions, or it is in any case filling a different nice from LRS, I'm more than happy to publish it. Could you please check?
Thanks.

**Comment by klausib** [comment]
The EventLayer Plugin can use any loaded QGIS Layer that has M Vaules, and any QGIS Layer that has even no M Values. Because QGIS could not handle M Values in Version privious 2.14 I guess, but I am sure not in Versions up to 2.8.. If this functionality is no longer needed,  its not obligatory necessary to keep it public anyway.

**Comment by pcav** [comment]
I'm exactly trying to understand whether this functionality is already available in LRS or not.

**Comment by pcav** [comment]
I'd be grateful if you could check LRS plugin for this, if you have time (just watching the video tutorial might be enough).
Thanks.

**Comment by klausib** [comment]
I did and I'm astonished - seems to be a kind of Copy of the EventLayer Plugin.  It's not clear (in this video - I have no sound), wheather these layers are Postgis layer or not. Strange, because I'm pretty certain, that the EventLayer Plugin is older. So again and according to this suggestion (or fact?), theoretically you should send the questions you ask me to the author of the LSR Plugin, because it seems that it was uploaded afterwards. Nevertheless, I have to contact Marco from Sourceploe and ask him for his opinon about this - he is the original author of the EventLayer Plugin.

**Comment by pcav** [comment]
@blazek your comments would be much appreciated

**Comment by blazek** [comment]
@klausib please think twice before calling someone's work a copy

The main purpose of the LRS plugin is to create and maintain LRS (i.e. lines with measures) from routes (without measures) and milestones. As a side effect, it can also generate events (which is simple). Currently it does not support creating events from existing line layer with measures, because QGIS was not supporting measures when the LRS plugin was writen.

**Comment by pcav** [comment]
So the plugin has a purpose, at least until measure support will be added to LRS.
Klaus, did you remove it from the repo?

**Comment by klausib** [comment]
@blazek Oh, sorry - "a kind of Copy" referred to the LRS Plugins' functionality, not to your or someone else's work.

Yes, Marco and I decided to remove it.

**Comment by pcav** [comment]
Pity, from our analysis it turned out that the plugin has indeed a functionaliyt (handling of M values) which is missing from LRS. If you reconsider your choice I'll be glad of publishing it. Of course, the ideal solution is to add the functionality to what appears (please correct me if I'm wrong) the most complete plugin.
Thanks.

**Comment by klausib** [comment]
That could be done. Simply have a look at the "QgsGeometryAnalyzer()" Class and the "eventLayer" public member function. The result can be stored directly into the QGIS Project file (QgsProject.instance().writeEntry("EventLayer",,,,)) to be dynamically regenerated whenever the Project is opend again.
